version: '3.6'

services: 
  smart-brain-api:
    container_name: backend
    # image: node:alpine
    build: ./
    command: npm start
    working_dir: /usr/src/smart_brain_api
    ports: 
      - "3000:3000"
