version: '3.6'

services: 
  # Backend API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart_brain_api
    ports: 
      - "3000:3000"
    volumes: 
      - ./:/usr/src/smart_brain_api
    
  # Postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
